#!/bin/bash -ex
overlay=$(mktemp -d)
default_options="--output=sgd_hybrid.iso $overlay"
mkdir -p "$overlay/boot/grub/"
cp menus/* "$overlay/boot/grub/"
mkdir -p "$overlay/boot/grub/trans"
cp trans/* "$overlay/boot/grub/trans"
grub-mkrescue $default_options "$@"
rm -r "$overlay"
