#!/bin/bash

SUPER_GRUB2_DISK_FILE_PREFIX="super_grub2_disk"

DEBIAN_GRUB2_SRC_DIR="/home/adrian/gnu/sgd/debian_grub2/grub2-2.00"

SGD2_SOURCE_DIR="$(pwd)"

function grub2_src_prepare () {
  make clean
  make distclean
  bash linguas.sh
  bash autogen.sh
}

function build_sg2d () {

  ./supergrub-mkrescue -o="${SUPER_GRUB2_DISK_FILE_PREFIX}_${TARGET_PLATFORM}_${sgrub_version}.iso"

}

function clean_every_build () {

  sudo rm -rf /usr/local/share/grub
  sudo rm -rf /usr/local/lib/grub
  grub2_src_prepare
  ./configure --target=i386 --with-platform=efi && make && sudo make uninstall
  make clean
  make distclean
  ./configure --target=i386 --with-platform=pc && make && sudo make uninstall
  make clean
  make distclean
  ./configure --target=x86_64 --with-platform=efi && make && sudo make uninstall
  make clean
  make distclean

}


function grub2_sg2d_hybrid_build () {

  # Grub2 - Hybrid build

  cd ${DEBIAN_GRUB2_SRC_DIR}
  clean_every_build
  grub2_src_prepare
  ./configure --target=i386 --with-platform=pc && make && sudo make install
  make clean
  make distclean
  ./configure --target=x86_64 --with-platform=efi && make && sudo make install
  cd ${SGD2_SOURCE_DIR}

  # Super Grub2 Disk - Hybrid build
  TARGET_PLATFORM="hybrid"
  build_sg2d

}

function grub2_sg2d_i386_pc_build () {

  # Grub2 - i386 - pc build
  cd ${DEBIAN_GRUB2_SRC_DIR}
  clean_every_build
  grub2_src_prepare
  bash lingua.sh
  bash autogen.sh
  ./configure --target=i386 --with-platform=pc && make && sudo make install
  cd ${SGD2_SOURCE_DIR}

  # Super Grub2 Disk - i386 - pc build
  TARGET_PLATFORM="i386_pc"
  build_sg2d

}

function grub2_sg2d_x86_64_efi_build () {

  # Grub2 - x86_64 - efi build
  cd ${DEBIAN_GRUB2_SRC_DIR}
  clean_every_build
  grub2_src_prepare
  ./configure --target=x86_64 --with-platform=efi && make && sudo make install
  cd ${SGD2_SOURCE_DIR}

  # Super Grub2 Disk - x86_64 - efi build
  TARGET_PLATFORM="x86_64_efi"
  build_sg2d

}

function grub2_sg2d_i386_efi_build () {

  # Grub2 - i386 - efi build
  cd ${DEBIAN_GRUB2_SRC_DIR}
  clean_every_build
  grub2_src_prepare
  ./configure --target=i386 --with-platform=efi && make && sudo make install
  cd ${SGD2_SOURCE_DIR}

  # Super Grub2 Disk - i386 - efi build
  TARGET_PLATFORM="i386_efi"
  build_sg2d

}


if [ ! -d "${DEBIAN_GRUB2_SRC_DIR}" ] ; then

  echo -e -n "Please set up a valid path for Debian Grub2 source code in this same file: ${0}\n"

fi

# Needed for getting SG2D version
source menus/version.cfg

grub2_sg2d_x86_64_efi_build

grub2_sg2d_i386_pc_build

grub2_sg2d_i386_efi_build

grub2_sg2d_hybrid_build

