#!/bin/bash

SUPER_GRUB2_DISK_FILE_PREFIX="super_grub2_disk"

DEBIAN_GRUB2_SRC_DIR="/home/adrian/gnu/sgd/debian_grub2/grub2-2.00"

SGD2_SOURCE_DIR="$(pwd)"

function build_sg2d () {

  ./supergrub-mkrescue -o="${SUPER_GRUB2_DISK_FILE_PREFIX}_${TARGET_PLATFORM}_${sgrub_version}.iso"

}

function clean_every_build () {


  ./configure --target=i386 --with-platform=efi && make && sudo make uninstall && make clean
  ./configure --target=i386 --with-platform=pc && make && sudo make uninstall && make clean
  ./configure --target=x86_64 --with-platform=efi && make && sudo make uninstall && make clean

}



if [ ! -d "${DEBIAN_GRUB2_SRC_DIR}" ] ; then

  echo -e -n "Please set up a valid path for Debian Grub2 source code in this same file: ${0}\n"

fi

# Needed for getting SG2D version
source menus/version.cfg

# Grub2 - Hybrid build

cd ${DEBIAN_GRUB2_SRC_DIR}
clean_every_build
./configure --target=i386 --with-platform=pc && make && sudo make install && make clean
./configure --target=x86_64 --with-platform=efi && make && sudo make install && make clean
cd ${SGD2_SOURCE_DIR}

# Super Grub2 Disk - Hybrid build
TARGET_PLATFORM="hybrid"
build_sg2d

# Grub2 - i386 - pc build
cd ${DEBIAN_GRUB2_SRC_DIR}
clean_every_build
./configure --target=i386 --with-platform=pc && make && sudo make install && make clean
cd ${SGD2_SOURCE_DIR}

# Super Grub2 Disk - i386 - pc build
TARGET_PLATFORM="i386_pc"
build_sg2d

# Grub2 - x86_64 - efi build
cd ${DEBIAN_GRUB2_SRC_DIR}
clean_every_build
./configure --target=x86_64 --with-platform=efi && make && sudo make install && make clean
cd ${SGD2_SOURCE_DIR}

# Super Grub2 Disk - x86_64 - efi build
TARGET_PLATFORM="x86_64_efi"
build_sg2d

# Grub2 - i386 - efi build
cd ${DEBIAN_GRUB2_SRC_DIR}
clean_every_build
./configure --target=i386 --with-platform=efi && make && sudo make install && make clean
cd ${SGD2_SOURCE_DIR}

# Super Grub2 Disk - i386 - efi build
TARGET_PLATFORM="i386_efi"
build_sg2d
