#!/bin/bash

SUPER_GRUB2_DISK_FILE_PREFIX="super_grub2_disk"

export DEBIAN_FRONTEND=noninteractive

SGD2_SOURCE_DIR="$(pwd)"

function build_sg2d () {

  ./supergrub-mkrescue -o="${SUPER_GRUB2_DISK_FILE_PREFIX}_${TARGET_PLATFORM}_${sgrub_version}.iso"

}

function build_sg2d_standalone () {

  ./supergrub-mkstandalone  \
    -O=${STANDALONE_FORMAT} \
    -o="${SUPER_GRUB2_DISK_FILE_PREFIX}\
_standalone_\
${STANDALONE_FORMAT_STR}_${sgrub_version}.${STANDALONE_EXTENSION}"

}

function clean_every_build () {

  sudo apt-get -y remove grub-.*-bin

}


function grub2_sg2d_hybrid_build () {

  # Grub2 - Hybrid build
  clean_every_build
  sudo apt-get -y install \
  grub-pc-bin \
  grub-efi-amd64-bin

  # Super Grub2 Disk - Hybrid build
  TARGET_PLATFORM="hybrid"
  build_sg2d

}

function grub2_sg2d_i386_pc_build () {

  # Grub2 - i386 - pc build
  clean_every_build
  sudo apt-get -y install \
  grub-pc-bin

  # Super Grub2 Disk - i386 - pc build
  TARGET_PLATFORM="i386_pc"
  build_sg2d

}

function grub2_sg2d_x86_64_efi_build () {

  # Grub2 - x86_64 - efi build
  clean_every_build
  sudo apt-get -y install \
  grub-efi-amd64-bin

  # Super Grub2 Disk - x86_64 - efi build
  TARGET_PLATFORM="x86_64_efi"
  build_sg2d

  STANDALONE_FORMAT_STR="x86_64_efi"
  STANDALONE_FORMAT="x86_64-efi"
  STANDALONE_EXTENSION="EFI"
  build_sg2d_standalone

}

function grub2_sg2d_i386_efi_build () {

  # Grub2 - i386 - efi build
  clean_every_build
  sudo apt-get -y install \
  grub-efi-ia32-bin

  # Super Grub2 Disk - i386 - efi build
  TARGET_PLATFORM="i386_efi"
  build_sg2d

  STANDALONE_FORMAT_STR="i386_efi"
  STANDALONE_FORMAT="i386-efi"
  STANDALONE_EXTENSION="EFI"
  build_sg2d_standalone

}

function grub2_sg2d_coreboot_build () {

  # Grub2 - coreboot build
  clean_every_build
  sudo apt-get -y install \
  grub-coreboot-bin

  # Super Grub2 Disk - coreboot build
  TARGET_PLATFORM="coreboot"
  build_sg2d

  STANDALONE_FORMAT_STR="i386_coreboot"
  STANDALONE_FORMAT="i386-coreboot"
  STANDALONE_EXTENSION="img"
  build_sg2d_standalone

}

function grub2_sg2d_ieee1275_build () {

  # Grub2 - ieee1275 build
  clean_every_build
  sudo apt-get -y install \
  grub-ieee1275-bin

  # Super Grub2 Disk - ieee1275 build
  TARGET_PLATFORM="ieee1275"
  build_sg2d

  STANDALONE_FORMAT_STR="i386_ieee1275"
  STANDALONE_FORMAT="i386-ieee1275"
  STANDALONE_EXTENSION="img"
  build_sg2d_standalone

}


# Needed for getting SG2D version
source menus/version.cfg

grub2_sg2d_hybrid_build

grub2_sg2d_x86_64_efi_build

grub2_sg2d_i386_pc_build

grub2_sg2d_i386_efi_build

grub2_sg2d_coreboot_build

grub2_sg2d_ieee1275_build
