#!/bin/bash
# Super Grub Disk - update_po
# Copyright (C) 2009,2010,2011,2012,2013,2014,2015  Adrian Gibanel Lopez.
#
# Super Grub Disk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Super Grub Disk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Super Grub Disk.  If not, see <http://www.gnu.org/licenses/>.

# This script updates po/sgrub.pot using xgettext, then updates all po/*.po
# using msgmerge. It should be run after adding / changing any translated strings.
# If you've added a new file which has translated strings, make sure to add it to
# gettext_file_list.

xgettext --files-from=xgettext_file_list --language=shell --output=po/sgrub.pot
for pofile in po/*.po; do
  msgmerge "$pofile" po/sgrub.pot -U
done
